import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'

const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgresql://oils:oils@localhost:5432/oils' })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter } as any)

// ─── Oil Definitions ──────────────────────────────────────────────────────────

const CARRIER_OILS = [
  {
    name: 'Sweet Almond',
    botanicalName: 'Prunus dulcis',
    origin: 'Mediterranean, Middle East',
    history: 'Used for thousands of years in Ayurvedic medicine and Middle Eastern beauty rituals, sweet almond oil was a luxury commodity traded along ancient spice routes. It was prized by Roman and Greek physicians for its emollient properties.',
    description: 'A light to medium-weight oil with excellent slip and glide, making it the most popular massage carrier worldwide. It absorbs at a medium rate, leaving skin smooth without excessive greasiness.',
    benefits: ['Deeply moisturising for all skin types', 'Excellent slip for massage strokes', 'Rich in vitamin E and oleic acid', 'Softens and conditions skin', 'Suitable for sensitive and dry skin'],
    contraindications: ['Avoid with nut allergies', 'May go rancid quickly — store in cool, dark place'],
    aroma: 'mild, slightly sweet, nutty',
    consistency: 'light',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Jojoba',
    botanicalName: 'Simmondsia chinensis',
    origin: 'Sonoran Desert, USA and Mexico',
    history: 'Native Americans of the Sonoran Desert have used jojoba for centuries, heating the seeds to produce a butter-like substance for skin and hair care. It became widely commercially produced in the 1970s as a sustainable alternative to sperm whale oil.',
    description: 'Technically a liquid wax rather than an oil, jojoba closely mimics the skin\'s natural sebum. It is extremely stable with a very long shelf life, making it ideal as a base for blends intended to be stored.',
    benefits: ['Mimics natural skin sebum', 'Non-comedogenic — won\'t clog pores', 'Exceptional shelf stability', 'Balances oily and dry skin', 'Deeply penetrating and conditioning'],
    contraindications: [],
    aroma: 'very faint, waxy, neutral',
    consistency: 'light',
    absorbency: 'medium',
    shelfLifeMonths: 24,
  },
  {
    name: 'Fractionated Coconut',
    botanicalName: 'Cocos nucifera',
    origin: 'Tropical coastal regions worldwide',
    history: 'Coconut oil has been used throughout tropical Asia and the Pacific for over 4,000 years. The fractionated form, which removes long-chain fatty acids to keep it liquid at room temperature, was developed in the 20th century specifically for therapeutic and cosmetic applications.',
    description: 'Fractionated coconut oil is a lightweight, colourless, and odourless carrier that remains liquid at room temperature unlike its virgin counterpart. It is highly stable and provides excellent glide, making it a popular choice for sports and therapeutic massage.',
    benefits: ['Nearly odourless — neutral base for scented blends', 'Very long shelf life', 'Lightweight and non-greasy', 'Excellent glide for deep tissue work', 'Hydrating without blocking pores'],
    contraindications: [],
    aroma: 'virtually odourless',
    consistency: 'light',
    absorbency: 'fast',
    shelfLifeMonths: 24,
  },
  {
    name: 'Grapeseed',
    botanicalName: 'Vitis vinifera',
    origin: 'Mediterranean Europe',
    history: 'A by-product of wine production, grapeseed oil has been used in European folk medicine since the Renaissance. Its widespread commercial use as a cosmetic carrier began in the late 20th century as the wine industry sought to valorise production waste.',
    description: 'One of the lightest carrier oils available, grapeseed absorbs quickly and leaves virtually no residue. Its high linoleic acid content makes it particularly suitable for oily, acne-prone, or combination skin types.',
    benefits: ['Ultra-lightweight and fast absorbing', 'High in antioxidant proanthocyanidins', 'Suitable for oily and combination skin', 'Tightens and tones skin mildly', 'Affordable and widely available'],
    contraindications: ['Short shelf life — use within 6 months of opening'],
    aroma: 'very faint, slightly green',
    consistency: 'light',
    absorbency: 'fast',
    shelfLifeMonths: 6,
  },
  {
    name: 'Argan',
    botanicalName: 'Argania spinosa',
    origin: 'Morocco',
    history: 'Known as "liquid gold" in Morocco, argan oil has been used by Berber women for centuries as a skin, hair, and culinary treatment. The labour-intensive hand-extraction process, traditionally performed by cooperatives of women, contributes to its high value and cultural significance.',
    description: 'Rich in tocopherols, polyphenols, and essential fatty acids, argan is one of the most nutrient-dense carrier oils. It absorbs readily and imparts a silky finish, making it an excellent addition to luxury facial and body blends.',
    benefits: ['Extremely rich in vitamin E', 'Anti-ageing and skin regenerating', 'Reduces appearance of stretch marks and scars', 'Silky non-greasy finish', 'Anti-inflammatory properties'],
    contraindications: ['Premium cost — often best used blended with a lighter carrier'],
    aroma: 'mild, slightly nutty',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 24,
  },
  {
    name: 'Rosehip Seed',
    botanicalName: 'Rosa canina / Rosa rubiginosa',
    origin: 'Chile, South America',
    history: 'Used by the Mayans and indigenous South American peoples for its remarkable wound-healing properties, rosehip seed oil gained global recognition following clinical studies in the 1980s demonstrating its effectiveness on scars and post-surgical tissue.',
    description: 'One of the richest plant sources of trans-retinoic acid and essential fatty acids, rosehip seed oil is a powerful skin regenerator. It is dry and fast absorbing, but should not be used on active acne due to its high linoleic content.',
    benefits: ['Exceptional skin regeneration', 'Reduces hyperpigmentation and scarring', 'Rich in natural vitamin A (trans-retinoic acid)', 'Anti-ageing and collagen-supportive', 'Treats dry, ageing, or damaged skin'],
    contraindications: ['Avoid on active breakouts or acne-prone skin', 'May oxidise quickly — refrigerate after opening', 'Photosensitising — do not apply before sun exposure'],
    aroma: 'distinctive, slightly earthy, fruity',
    consistency: 'light',
    absorbency: 'fast',
    shelfLifeMonths: 6,
  },
  {
    name: 'Apricot Kernel',
    botanicalName: 'Prunus armeniaca',
    origin: 'China, Central Asia',
    history: 'Originating in China over 4,000 years ago, apricot kernel oil spread along the Silk Road to Persia and eventually Europe. It has been a staple of traditional Chinese medicine and Persian cosmetic practice for its skin-softening properties.',
    description: 'A light, versatile oil very similar to sweet almond but with a slightly finer texture and lighter colour. It is particularly well-suited to facial massage and dry or sensitive skin conditions, absorbing smoothly without greasiness.',
    benefits: ['Excellent for facial massage', 'Softening and soothing for sensitive skin', 'Rich in oleic and linoleic acids', 'Helps maintain skin elasticity', 'Good substitute for sweet almond with nut allergies (seed-derived)'],
    contraindications: ['Not suitable for severe tree nut allergies (always patch test)'],
    aroma: 'very light, faintly sweet',
    consistency: 'light',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Avocado',
    botanicalName: 'Persea americana',
    origin: 'Central America, Mexico',
    history: 'The Aztec civilisation used avocado oil extensively for skin and hair care. Avocados themselves have been cultivated for over 5,000 years in Mesoamerica, and the oil was considered sacred for its nourishing properties.',
    description: 'A heavy, viscous carrier rich in vitamins A, D, and E with a distinctive dark green colour. It is best used in small proportions blended with lighter carriers, as its weight and viscosity can impede massage flow in larger quantities.',
    benefits: ['Deeply penetrating and nourishing', 'High in vitamins A, D, and E', 'Excellent for mature or very dry skin', 'Contains avocadin for skin support', 'Supports wound healing and skin repair'],
    contraindications: ['Very heavy — use at 10–20% max in massage blends', 'Strong colour may stain linens'],
    aroma: 'mild, buttery, faintly green',
    consistency: 'heavy',
    absorbency: 'slow',
    shelfLifeMonths: 12,
  },
  {
    name: 'Sunflower Seed',
    botanicalName: 'Helianthus annuus',
    origin: 'North America',
    history: 'Sunflowers were cultivated by Native American tribes over 3,000 years ago, who used the seeds for food and the extracted oil for skin and hair. Commercial production expanded dramatically in Europe during the 18th and 19th centuries.',
    description: 'A light to medium carrier rich in linoleic acid with excellent emollient properties. It is affordable, widely available, and makes an excellent everyday massage base particularly for normal to oily skin types.',
    benefits: ['Rich in linoleic acid for skin barrier support', 'Lightweight emollient for all skin types', 'Affordable workhorse base oil', 'Contains natural vitamin E', 'Good for eczema and psoriasis-prone skin'],
    contraindications: ['Short shelf life — use within 6 months', 'Avoid with sunflower seed allergy'],
    aroma: 'very mild, faintly nutty',
    consistency: 'light',
    absorbency: 'medium',
    shelfLifeMonths: 6,
  },
  {
    name: 'Hemp Seed',
    botanicalName: 'Cannabis sativa',
    origin: 'Central Asia',
    history: 'One of humanity\'s oldest cultivated plants, hemp has been used therapeutically in China for at least 3,000 years. Hemp seed oil has experienced a significant renaissance in cosmetics and wellness since the early 2000s due to its remarkable fatty acid profile.',
    description: 'Contains an almost perfect 3:1 ratio of omega-6 to omega-3 fatty acids, matching the optimal profile for human skin health. Its distinctive green colour and earthy aroma mean it is often used blended with lighter neutral carriers.',
    benefits: ['Ideal omega-6:3 fatty acid ratio for skin', 'Anti-inflammatory properties', 'Excellent for eczema and psoriasis', 'Supports skin barrier function', 'Rich in gamma-linolenic acid (GLA)'],
    contraindications: ['Short shelf life — refrigerate', 'Distinctive colour and aroma limits some blends', 'Trace THC — not for use with professional drug testing concerns'],
    aroma: 'earthy, grassy, slightly nutty',
    consistency: 'light',
    absorbency: 'fast',
    shelfLifeMonths: 6,
  },
  {
    name: 'Castor',
    botanicalName: 'Ricinus communis',
    origin: 'East Africa, India',
    history: 'Used in ancient Egypt as a lamp oil, cosmetic, and medicine for over 4,000 years, castor oil was applied by Cleopatra to improve the lustre of her eyes. It became a globally important industrial and medicinal oil through the 19th century.',
    description: 'An extremely viscous, thick carrier with unique properties due to its high ricinoleic acid content. It is almost never used neat in massage — typically blended at 5–10% with lighter carriers to add thickness and drawing properties.',
    benefits: ['Deeply conditioning and occlusive', 'Stimulates circulation when applied with massage', 'Excellent for dry, cracked skin', 'Antimicrobial properties', 'Draws toxins and supports lymphatic drainage'],
    contraindications: ['Never use neat in massage — too viscous, intensifies EO absorption', 'Can cause laxative effect if ingested', 'Avoid with sensitive skin in concentration above 10%'],
    aroma: 'mild, faintly musty',
    consistency: 'heavy',
    absorbency: 'slow',
    shelfLifeMonths: 60,
  },
  {
    name: 'Marula',
    botanicalName: 'Sclerocarya birrea',
    origin: 'Sub-Saharan Africa',
    history: 'Marula oil has been used by southern African communities including the San and Zulu peoples for centuries as a skin moisturiser, leather conditioner, and food preservative. It has gained international recognition as a luxury beauty ingredient since the early 2000s.',
    description: 'An exceptionally stable carrier with an oleic acid content exceeding 70%, marula absorbs rapidly while leaving a luxurious silky feel. It is particularly prized for facial massage and mature skin formulations.',
    benefits: ['Exceptional stability and shelf life', 'Rapidly absorbing with a silky finish', 'Rich in amino acids for skin repair', 'Anti-ageing properties', 'Sustainably and ethically sourced from Africa'],
    contraindications: ['Premium price point'],
    aroma: 'mild, slightly nutty',
    consistency: 'light',
    absorbency: 'fast',
    shelfLifeMonths: 24,
  },
  {
    name: 'Tamanu',
    botanicalName: 'Calophyllum inophyllum',
    origin: 'Polynesia, Southeast Asia',
    history: 'Used by the peoples of Polynesia, Southeast Asia, and South Asia for millennia, tamanu oil was a cornerstone of traditional medicine for treating skin diseases, nerve pain, and infected wounds. It remains an important ceremonial and medicinal oil in many Pacific Island cultures.',
    description: 'One of the most therapeutically powerful carrier oils, tamanu contains the unique compound calophyllolide which exhibits strong anti-inflammatory and wound-healing properties. Its distinctive dark green colour and strong aroma mean it is usually blended at 10–25% with other carriers.',
    benefits: ['Exceptional wound healing and tissue regeneration', 'Strong anti-inflammatory (calophyllolide)', 'Effective for nerve pain and neuralgia', 'Antifungal and antimicrobial', 'Treats eczema, psoriasis, and rosacea'],
    contraindications: ['Avoid with nut allergies (calophyllum family)', 'Strong aroma and colour — use as secondary carrier', 'Patch test essential due to sensitisation potential'],
    aroma: 'strong, green, slightly medicinal',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 24,
  },
  {
    name: 'Pomegranate Seed',
    botanicalName: 'Punica granatum',
    origin: 'Persia (modern Iran), Himalayas',
    history: 'Pomegranate has been cultivated for over 4,000 years and was revered in ancient Persia, Egypt, and Greece as a symbol of fertility and immortality. The seed oil has been used in Persian cosmetic traditions for centuries as a premium skin treatment.',
    description: 'One of the most unusual carrier oils, pomegranate seed oil is the only plant-derived oil containing predominantly conjugated fatty acids (punicic acid). It is a powerful antioxidant and anti-ageing carrier typically used at 10–20% in blends.',
    benefits: ['Unique punicic acid content — powerful antioxidant', 'Stimulates keratinocyte proliferation for skin renewal', 'Anti-ageing and sun damage repair', 'Supports collagen production', 'Anti-inflammatory for sensitive skin'],
    contraindications: ['Expensive — best used at 10–20% in blends', 'Short shelf life once opened'],
    aroma: 'mild, slightly tart and fruity',
    consistency: 'light',
    absorbency: 'fast',
    shelfLifeMonths: 12,
  },
  {
    name: 'Evening Primrose',
    botanicalName: 'Oenothera biennis',
    origin: 'North America',
    history: 'Used by Native American tribes for food and medicine for centuries, evening primrose gained widespread therapeutic recognition in the 1980s following research into its unique GLA (gamma-linolenic acid) content and its role in hormonal balance and skin health.',
    description: 'Exceptionally high in gamma-linolenic acid (GLA), evening primrose is primarily used as an active therapeutic carrier at 10–25% alongside lighter base oils. It is particularly valued for hormonal skin conditions and inflammatory skin disorders.',
    benefits: ['Exceptionally high in GLA for skin balance', 'Therapeutic for hormonal skin conditions', 'Anti-inflammatory for eczema and psoriasis', 'Supports cell membrane integrity', 'Beneficial for PMS-related tension massage'],
    contraindications: ['Short shelf life — keep refrigerated', 'Use as secondary carrier at 10–25% due to cost', 'Avoid with epilepsy at high internal doses (topical use is safe)'],
    aroma: 'very faint, slightly sweet',
    consistency: 'light',
    absorbency: 'medium',
    shelfLifeMonths: 6,
  },
  {
    name: 'Walnut',
    botanicalName: 'Juglans regia',
    origin: 'France, California, China',
    history: 'Walnut trees have been cultivated across Europe and Asia for millennia. The oil was cold-pressed in ancient Persia and Greece for both culinary and cosmetic use. It has long featured in French country medicine as a traditional skin treatment and was a staple trade good along early Mediterranean routes.',
    description: 'A medium-weight oil with a distinctive rich, earthy aroma and natural tawny colour. Rich in alpha-linolenic acid (omega-3) and polyphenol antioxidants, walnut oil has notable anti-inflammatory and antifungal properties. Best used blended with lighter carriers due to its characteristic colour and scent.',
    benefits: ['Rich in omega-3 alpha-linolenic acid', 'Anti-inflammatory for dry and irritated skin', 'Antifungal properties', 'Natural polyphenol antioxidant content', 'Supportive for eczema and psoriasis'],
    contraindications: ['Must not be used with nut allergies — high cross-reactivity risk', 'May cause slight skin staining due to natural pigmentation', 'Keep refrigerated — short shelf life', 'Patch test recommended'],
    aroma: 'rich, earthy, slightly nutty',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 6,
  },
  {
    name: "St John's Wort",
    botanicalName: 'Hypericum perforatum',
    origin: 'Europe, Western Asia',
    history: "One of Europe's most historically significant medicinal herbs, St John's Wort has been used since ancient Greece for wound healing and nerve pain. Medieval European physicians called it the 'arnica of the nerves.' The distinctive ruby-red hypericin pigment that leaches into the oil during infusion has been used as a wound treatment across multiple cultures for over 2,000 years.",
    description: "An infused (macerated) oil — typically sunflower or olive oil infused with the fresh flowers — with a characteristic deep ruby-red colour from hypericin. Powerfully anti-inflammatory and antineuralgic, it is one of the most important carriers for nerve-related pain, sciatica, sunburn, and post-injury recovery.",
    benefits: ['Powerful antineuralgic for nerve pain and sciatica', 'Anti-inflammatory for injured tissue', 'Promotes wound healing', 'Particularly effective for bruising and haematoma', 'Supports post-injury tissue recovery'],
    contraindications: ['Photosensitising — do not use before sun or UV exposure', 'May interact with many pharmaceutical medications — advise clients to check with pharmacist', 'Rich ruby colour may stain linens', 'Avoid in pregnancy'],
    aroma: 'faint, slightly floral, herbal',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Wheat Germ',
    botanicalName: 'Triticum vulgare',
    origin: 'Global (processed from wheat)',
    history: "Wheat germ oil became commercially significant in the early 20th century following the discovery of vitamin E (tocopherol) as an essential nutrient. It was widely used as a vitamin E supplement and skin treatment throughout the mid-20th century and remains the richest natural source of tocopherol available.",
    description: 'One of the richest natural sources of vitamin E (tocopherol), wheat germ is a heavy, intensely nourishing oil primarily used as an antioxidant additive (5–15%) in blends to extend shelf life and support skin cell renewal. Its strong, distinctive wheaty aroma makes it unsuitable as a primary carrier but invaluable as a protecting addition.',
    benefits: ['Highest natural tocopherol (vitamin E) content of any carrier', 'Powerful antioxidant — extends shelf life of other oils when blended', 'Deeply nourishing for very dry or mature skin', 'Supports skin elasticity and cell renewal', 'Protective against free radical damage'],
    contraindications: ['Avoid with wheat or gluten sensitivity (topical risk is low but caution advised)', 'Very heavy — use at 5–15% maximum in blends', 'Strong aroma limits use as a primary carrier', 'Short shelf life once opened'],
    aroma: 'strong, wheaty, earthy',
    consistency: 'heavy',
    absorbency: 'slow',
    shelfLifeMonths: 6,
  },
  {
    name: 'Comfrey',
    botanicalName: 'Symphytum officinale',
    origin: 'Europe, Western Asia',
    history: "Known as 'knitbone' in medieval European herbal medicine, comfrey has a 2,500-year history of use for broken bones, sprains, and wounds. Its Latin name Symphytum means 'to join together.' The active compound allantoin, identified in the 19th century, confirmed its traditional reputation for accelerating tissue repair.",
    description: 'An infused oil — typically sunflower or olive oil macerated with comfrey root or leaves — prized for its high allantoin content. Allantoin promotes cell proliferation and accelerates tissue healing, making comfrey one of the most powerful carriers for musculoskeletal injuries, sprains, bruising, and sports recovery.',
    benefits: ['High allantoin content for accelerated tissue repair', 'Anti-inflammatory for joints and muscles', 'Reduces pain and swelling from sprains and strains', 'Promotes bone-adjacent soft tissue healing', 'Excellent for sports injury recovery massage'],
    contraindications: ['Never use on broken or open skin — can trap bacteria and cause abscess', 'Not for use in pregnancy', 'Avoid prolonged use over large body areas (pyrrolizidine alkaloid content — check supplier processing standards)', 'Not for internal use'],
    aroma: 'faint, slightly green, earthy',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Neem',
    botanicalName: 'Azadirachta indica',
    origin: 'India, South Asia',
    history: "The neem tree has been called the 'village pharmacy' in India and features in ancient Sanskrit medical texts as a treatment for skin disease, fever, and infection. Used in Ayurvedic medicine for over 4,000 years, neem is deeply embedded in South Asian culture — every part of the tree is considered medicinal.",
    description: "One of the most therapeutically potent and aromatically distinctive carrier oils, neem has a uniquely powerful, sulphurous, garlic-like odour that makes it impractical to use undiluted in massage. It is typically blended at 5–10% with neutral carriers. Its insecticidal, antifungal, and antimicrobial properties are exceptional and unmatched by any other carrier oil.",
    benefits: ['Exceptional antifungal and antimicrobial properties', 'Powerful insecticidal action', 'Highly effective for chronic skin conditions — eczema, psoriasis', 'Anti-inflammatory and wound-healing', 'One of the best carriers for scalp conditions and dandruff'],
    contraindications: ['Very strong pungent odour — always blend at 5–10% maximum; obtain client consent', 'Avoid in pregnancy', 'Avoid near eyes or mucous membranes', 'Not for internal use'],
    aroma: 'pungent, sulphurous, garlic-like, medicinal',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 24,
  },
  {
    name: 'Macadamia',
    botanicalName: 'Macadamia integrifolia / Macadamia tetraphylla',
    origin: 'Australia, Hawaii',
    history: 'Macadamia nuts are native to the subtropical rainforests of northeastern Australia, where they were a staple food of Aboriginal Australians for thousands of years. Commercial cultivation expanded in Hawaii from the late 19th century. The oil\'s unique palmitoleic acid content was identified in the 20th century, establishing it as a specialist carrier for mature skin.',
    description: "Uniquely rich in palmitoleic acid (omega-7) — a monounsaturated fatty acid that declines naturally with skin ageing — macadamia oil replenishes what the skin loses over time, making it one of the most skin-compatible carriers for mature complexions. It has a silky, medium-weight texture and excellent shelf stability.",
    benefits: ['Uniquely high palmitoleic acid (omega-7) content', 'Exceptionally compatible with mature and ageing skin', 'Replenishes age-depleting skin lipids', 'Excellent slip and silky finish', 'Well-tolerated even by sensitive skin'],
    contraindications: ['Nut allergy risk — patch test essential', 'Higher cost — often blended with lighter carriers to extend'],
    aroma: 'very mild, faintly nutty',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Calendula',
    botanicalName: 'Calendula officinalis',
    origin: 'Mediterranean, Central Europe',
    history: "Calendula — known as 'pot marigold' — has been used medicinally across Europe and the Mediterranean since at least the 12th century. Medieval physicians used it extensively for skin conditions, wounds, and as an anti-inflammatory. Its name derives from the Latin 'calendae,' as it was observed to bloom on the first of many calendar months. It remained a standard wound treatment in field hospitals as recently as the American Civil War.",
    description: 'An infused oil — typically sunflower or olive oil macerated with the flowers — rich in carotenoids, flavonoids, and terpenoids. One of the gentlest and most broadly soothing carriers available, calendula is particularly valued for baby massage, eczema, very sensitive skin, post-procedure skin recovery, and any condition involving inflammation or irritation.',
    benefits: ['Exceptionally gentle and soothing for sensitive skin', 'Anti-inflammatory for eczema and dermatitis', 'Promotes wound healing and skin repair', 'Rich in carotenoids and flavonoids', 'Ideal for baby massage and post-procedure skin care'],
    contraindications: ['Avoid with Asteraceae (daisy family) allergy', 'Check for ragweed cross-reactivity in susceptible clients', 'Golden carotenoid colour may mark light linens'],
    aroma: 'faint, warm, slightly herbal',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Borage Seed',
    botanicalName: 'Borago officinalis',
    origin: 'Mediterranean Europe, introduced widely',
    history: 'Borage has been cultivated in Mediterranean Europe since antiquity and widely used in medieval European herbal medicine. The oil from its seeds — identified as the richest known plant source of GLA — became commercially significant in the 1980s alongside evening primrose, for similar hormonal and inflammatory skin applications.',
    description: 'Contains the highest GLA (gamma-linolenic acid) content of any plant oil — typically 20–25%, approximately double that of evening primrose. Used as a therapeutic additive at 10–25% in blends for inflammatory skin conditions, hormonal skin concerns, and anti-ageing formulations.',
    benefits: ['Highest plant GLA content — typically 20–25%', 'Powerful anti-inflammatory for eczema and dermatitis', 'Supports hormonal skin balance', 'Promotes skin cell regeneration', 'Complements evening primrose in therapeutic blends'],
    contraindications: ['Very short shelf life — refrigerate and use quickly after opening', 'Use as secondary carrier at 10–25%', 'Pyrrolizidine alkaloids in the plant — ensure well-processed, PA-free oil'],
    aroma: 'very faint, slightly green',
    consistency: 'light',
    absorbency: 'medium',
    shelfLifeMonths: 6,
  },
  {
    name: 'Arnica',
    botanicalName: 'Arnica montana',
    origin: 'European Alps, Siberia, North America',
    history: "Known as 'mountain tobacco' and 'fall herb' across the European Alps, arnica has been a cornerstone of European folk medicine for at least 500 years. Homeopathic arnica was codified in the 18th century. It remains one of the most widely recognised herbal remedies for bruising and sports injuries globally, and is a near-universal addition to sports first-aid kits.",
    description: 'An infused oil — alpine flowers macerated in a base such as sunflower or olive oil — containing unique sesquiterpene lactones including helenalin. These compounds are responsible for its remarkable anti-inflammatory and anti-bruising properties, making arnica one of the most important oils in sports massage and post-injury care.',
    benefits: ['Exceptional anti-bruising and haematoma treatment', 'Powerful anti-inflammatory for sports injuries', 'Reduces swelling and pain from sprains and strains', 'Stimulates circulation in injured tissue', 'Reduces muscle soreness post-exercise'],
    contraindications: ['Never use on broken skin or open wounds', 'Avoid near eyes or mucous membranes', 'Avoid with Asteraceae (daisy family) allergy', 'Not for use in pregnancy', 'Not for internal use — helenalin is toxic if ingested'],
    aroma: 'faint, warm, herbal, slightly medicinal',
    consistency: 'medium',
    absorbency: 'medium',
    shelfLifeMonths: 12,
  },
  {
    name: 'Olive',
    botanicalName: 'Olea europaea',
    origin: 'Mediterranean',
    history: "Olive oil is among the most ancient and culturally significant oils in human history, with cultivation dating back over 6,000 years to the Eastern Mediterranean. Homer called it 'liquid gold.' Used in ancient Egypt, Greece, and Rome for cooking, lamp oil, religious ceremony, and body care, its use is documented in texts from every major ancient Mediterranean civilisation — including as a massage and skin conditioning treatment.",
    description: "The original massage and body oil of the ancient world, olive oil is deeply nourishing, rich in oleic acid, squalene, and polyphenol antioxidants. Its distinctive green aroma and heavy texture limit its use in modern blended massage, but it remains excellent for dry and mature skin, scalp and hair treatments, and holds enduring therapeutic significance.",
    benefits: ['Rich in oleic acid and squalene for deep moisturisation', 'High polyphenol antioxidant content', 'Traditional wound healing and skin conditioning', 'Excellent for very dry skin and hair treatments', 'Rich cultural therapeutic history — the original massage oil'],
    contraindications: ['Strong distinctive aroma — not universally acceptable in massage; check client preference', 'Heavy texture — blend with lighter carriers for most massage applications', 'Extra-virgin preferred for therapeutic use; refined has less aroma but fewer actives', 'May aggravate eczema in infants — avoid for baby massage'],
    aroma: 'distinctive, fruity, slightly grassy',
    consistency: 'heavy',
    absorbency: 'slow',
    shelfLifeMonths: 18,
  },
]

const ESSENTIAL_OILS = [
  {
    name: 'Lavender',
    botanicalName: 'Lavandula angustifolia',
    origin: 'France, Bulgaria, England',
    history: 'Lavender has been used for over 2,500 years, prized by Romans for bathing and laundering. During World War I, René-Maurice Gattefossé famously discovered its wound-healing properties after burning his hand and plunging it into lavender, founding the modern practice of aromatherapy.',
    description: 'The most versatile and widely used essential oil in aromatherapy, lavender balances and normalises rather than pushing in one direction. It is calming without being sedating at low doses, and has documented analgesic and anti-inflammatory properties relevant to massage.',
    benefits: ['Calming and anxiolytic', 'Analgesic for muscle tension', 'Promotes restful sleep', 'Anti-inflammatory', 'Gentle enough for most skin types'],
    contraindications: ['Avoid at high doses in first trimester', 'May cause drowsiness — avoid before driving'],
    aroma: 'floral, herbaceous, sweet',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Peppermint',
    botanicalName: 'Mentha × piperita',
    origin: 'Europe (hybrid species)',
    history: 'A natural hybrid of watermint and spearmint, peppermint has been used medicinally since at least ancient Egypt. Dried peppermint leaves have been found in Egyptian tombs dating to 1000 BCE. It was extensively cultivated in England from the 17th century for medicinal use.',
    description: 'One of the most stimulating and cooling essential oils, peppermint is widely used in sports massage for its analgesic and cooling properties. The high menthol content creates a pronounced cooling sensation followed by warmth, stimulating circulation.',
    benefits: ['Cooling and analgesic for muscle pain', 'Improves circulation and alertness', 'Relieves headaches when applied to temples', 'Decongestant and anti-inflammatory', 'Energising and mentally stimulating'],
    contraindications: ['Never use on children under 6 years old', 'Avoid near face and neck in concentration', 'Do not use before sleep — too stimulating', 'Avoid with epilepsy'],
    aroma: 'sharp, cool, mentholic',
    dilutionRateMax: 0.03,
  },
  {
    name: 'Eucalyptus',
    botanicalName: 'Eucalyptus globulus / Eucalyptus radiata',
    origin: 'Australia',
    history: 'Aboriginal Australians have used eucalyptus as a traditional medicine for thousands of years. Commercial distillation began in Victoria in the 1850s, and it rapidly became a globally important medicinal oil for respiratory and muscular conditions.',
    description: 'Rich in 1,8-cineole, eucalyptus is a powerful decongestant and anti-inflammatory with pronounced warming and cooling properties. Eucalyptus radiata is considered gentler and more suitable for massage than the more intense E. globulus.',
    benefits: ['Powerful decongestant and expectorant', 'Anti-inflammatory for joint and muscle pain', 'Antimicrobial properties', 'Cooling and refreshing', 'Improves focus and clears mental fatigue'],
    contraindications: ['Avoid on children under 10 near face and neck', 'Do not apply near nose or airways of infants', 'Avoid with epilepsy', 'Not for use with certain medications (immunosuppressants)'],
    aroma: 'sharp, camphoraceous, clean, medicinal',
    dilutionRateMax: 0.02,
  },
  {
    name: 'Tea Tree',
    botanicalName: 'Melaleuca alternifolia',
    origin: 'Australia (New South Wales)',
    history: 'The Bundjalung people of eastern Australia used tea tree leaves as a traditional medicine, crushing them to treat wounds and infections. Australian troops in World War II received tea tree oil in first aid kits. Modern antimicrobial research has extensively validated its traditional uses.',
    description: 'One of the best-researched essential oils, tea tree has broad-spectrum antimicrobial properties effective against bacteria, fungi, and some viruses. In massage, it is primarily used for its anti-inflammatory and skin-balancing properties rather than strong antimicrobial action.',
    benefits: ['Broad-spectrum antimicrobial', 'Anti-inflammatory for skin and joints', 'Antifungal for skin conditions', 'Immune-stimulating', 'Balancing for oily and acne-prone skin'],
    contraindications: ['Avoid oxidised oil — can cause sensitisation', 'Not for internal use', 'Patch test recommended for sensitive skin'],
    aroma: 'medicinal, camphorous, fresh',
    dilutionRateMax: 0.03,
  },
  {
    name: 'Rosemary',
    botanicalName: 'Rosmarinus officinalis (Salvia rosmarinus)',
    origin: 'Mediterranean',
    history: 'Rosemary has been a sacred and medicinal herb in Mediterranean cultures since antiquity. Ancient Greeks and Romans burned it for purification, and medieval European herbalists prescribed it for "memory strengthening." Its use in sports massage dates to Renaissance Europe.',
    description: 'A stimulating, warming essential oil particularly effective for muscular and joint conditions. It improves local circulation and has analgesic properties, making it a staple in sports massage, warming blends, and treatments for stiff or cold muscles.',
    benefits: ['Stimulates and warms muscles', 'Improves local circulation', 'Analgesic for muscle stiffness', 'Mentally stimulating and focus-enhancing', 'Supports scalp and hair health'],
    contraindications: ['Avoid in pregnancy', 'Avoid with epilepsy', 'Avoid with high blood pressure in high doses', 'Stimulating — avoid at bedtime'],
    aroma: 'herbaceous, camphoraceous, fresh, woody',
    dilutionRateMax: 0.04,
  },
  {
    name: 'Frankincense',
    botanicalName: 'Boswellia sacra / Boswellia carterii',
    origin: 'Oman, Somalia, Ethiopia',
    history: 'One of the most ancient of all aromatics, frankincense resin has been traded across the Arabian Peninsula for over 5,000 years. It was used in ancient Egypt for embalming and religious ritual, and features prominently in Ayurvedic, Chinese, and Biblical traditions. Modern research confirms its anti-inflammatory boswellic acids.',
    description: 'A deeply grounding and spiritually resonant oil with documented anti-inflammatory properties. It is often called the "king of oils" in aromatherapy, prized for its ability to slow and deepen breathing, ease anxiety, and support mature skin through cell regeneration.',
    benefits: ['Deeply grounding and meditative', 'Anti-inflammatory (boswellic acids)', 'Promotes cellular regeneration for skin', 'Eases anxiety and stress', 'Deepens and slows breathing'],
    contraindications: ['Avoid in first trimester (mild uterine stimulant)', 'May interact with blood thinning medications'],
    aroma: 'warm, balsamic, slightly citrus, sacred',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Roman Chamomile',
    botanicalName: 'Anthemis nobilis (Chamaemelum nobile)',
    origin: 'England, France, Belgium',
    history: 'Revered by ancient Egyptians who dedicated it to the sun god Ra, Roman chamomile has a centuries-long history in European herbal medicine. The name "chamomile" derives from the Greek for "ground apple," referencing its characteristic fruity aroma.',
    description: 'One of the gentlest and most soothing of all essential oils, Roman chamomile is particularly valuable for stress-related conditions, children\'s massage, and sensitive or inflamed skin. It is a powerful anti-inflammatory with notable calming effects on both mind and body.',
    benefits: ['Deeply calming and sedative', 'Powerful anti-inflammatory', 'Ideal for children and sensitive skin', 'Relieves anxiety and nervous tension', 'Soothes skin irritation and redness'],
    contraindications: ['Avoid in pregnancy (first trimester especially)', 'May cause drowsiness'],
    aroma: 'sweet, fruity, apple-like, herbaceous',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Ylang Ylang',
    botanicalName: 'Cananga odorata',
    origin: 'Philippines, Madagascar, Indonesia',
    history: 'The star-shaped flowers of the ylang ylang tree have been woven into bridal beds in Indonesia for centuries, where the oil is considered an aphrodisiac and romantic tradition. It is a key note in the classic perfume Chanel N°5 and is produced in significant volume in Madagascar.',
    description: 'An intensely floral, exotic oil with pronounced sedative and euphoric properties. It should be used sparingly — even at low dilutions it can be overwhelming and cause headaches in some people. Particularly useful for tension, anxiety, and blends with romantic intent.',
    benefits: ['Calming and euphoric', 'Lowers blood pressure', 'Eases anxiety and nervous tension', 'Traditionally used as an aphrodisiac', 'Regulates sebum for hair and skin'],
    contraindications: ['Use at very low dilution — can cause headaches in high amounts', 'May lower blood pressure excessively with medication', 'Avoid in pregnancy', 'Sensitisation risk in some individuals'],
    aroma: 'intensely floral, sweet, exotic, heady',
    dilutionRateMax: 0.02,
  },
  {
    name: 'Bergamot',
    botanicalName: 'Citrus bergamia',
    origin: 'Calabria, Italy',
    history: 'Named after the Italian city of Bergamo where it was first sold, bergamot oil has been used in Italian folk medicine since the early 18th century. It is the distinctive flavouring in Earl Grey tea and a core ingredient of classic eau de cologne formulations.',
    description: 'A uniquely uplifting citrus oil with both stimulating and calming properties — it brightens mood while reducing anxiety. The bergapten-free (FCF) version should always be used in massage to eliminate photosensitisation risk.',
    benefits: ['Uplifts mood and reduces anxiety simultaneously', 'Antidepressant properties', 'Antimicrobial for skin conditions', 'Digestive support', 'Balances and calms the nervous system'],
    contraindications: ['Always use bergapten-free (FCF) version for skin application', 'Photosensitising if non-FCF version is used', 'Avoid with citrus oil sensitisation'],
    aroma: 'bright citrus, floral, slightly spicy',
    dilutionRateMax: 0.04,
  },
  {
    name: 'Geranium',
    botanicalName: 'Pelargonium graveolens / Pelargonium x asperum',
    origin: 'South Africa, Egypt, Réunion',
    history: 'Native to South Africa, geranium was introduced to Europe in the 17th century and rapidly adopted into European herbal traditions. The variety grown on the island of Réunion (Bourbon geranium) is considered the finest for aromatherapy due to its complex, rose-like quality.',
    description: 'Often called "the poor person\'s rose," geranium oil offers a complex floral aroma with documented balancing and toning properties. It is particularly effective for hormonal skin conditions and is one of the best oils for balancing combination skin and supporting lymphatic massage.',
    benefits: ['Hormonal and emotional balancing', 'Toning and firming for skin', 'Supports lymphatic drainage', 'Antifungal properties', 'Relieves anxiety and PMS symptoms'],
    contraindications: ['Avoid in pregnancy', 'May cause sensitisation in some individuals', 'Not suitable for hormone-sensitive conditions (endometriosis) without guidance'],
    aroma: 'rose-like, sweet, green, slightly citrus',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Clary Sage',
    botanicalName: 'Salvia sclarea',
    origin: 'Southern Europe, Central Asia',
    history: 'Known as "clear eyes" in medieval Europe, clary sage was widely used by herbalists for eye treatments and as a uterine tonic. It has been a key herb in European women\'s medicine for centuries, used to regulate menstruation and ease childbirth.',
    description: 'A powerfully relaxing and antispasmodic oil with notable oestrogenic properties. It is one of the most effective oils for menstrual cramps and PMS-related tension, and creates a mild euphoric, intoxicating relaxation that makes it valuable for stress and anxiety massage.',
    benefits: ['Powerful antispasmodic for muscle cramps', 'Oestrogenic — supports hormonal balance', 'Deeply relaxing and mildly euphoric', 'Beneficial for menstrual pain', 'Reduces nervous tension and anxiety'],
    contraindications: ['Never use with alcohol — intensifies effects dramatically', 'Avoid in pregnancy', 'Avoid with hormone-sensitive conditions', 'Do not use before driving or operating machinery', 'Avoid with oestrogen-dependent cancers'],
    aroma: 'herbaceous, sweet, slightly musky, earthy',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Lemongrass',
    botanicalName: 'Cymbopogon citratus / Cymbopogon flexuosus',
    origin: 'India, Sri Lanka, Southeast Asia',
    history: 'A cornerstone of Ayurvedic medicine and traditional Thai healing for over 2,000 years, lemongrass has been used to treat fever, infections, and digestive disorders. Its cultivation spread throughout tropical regions with Indian and Southeast Asian trade routes.',
    description: 'A bright, citrus-green oil with strong toning and deodorising properties. In massage, it is particularly useful for tired, aching muscles and sports recovery. Its high citral content makes it potentially sensitising and should be used at lower dilutions.',
    benefits: ['Toning and firming for skin and connective tissue', 'Reduces muscle fatigue and soreness', 'Antimicrobial and deodorising', 'Improves circulation', 'Invigorating and mentally stimulating'],
    contraindications: ['Use at low dilution — sensitisation risk due to citral content', 'Avoid on damaged or inflamed skin', 'Avoid in pregnancy', 'Patch test essential'],
    aroma: 'bright, citrus, green, fresh, lemony',
    dilutionRateMax: 0.02,
  },
  {
    name: 'Clove Bud',
    botanicalName: 'Syzygium aromaticum',
    origin: 'Maluku Islands (Spice Islands), Indonesia',
    history: 'For centuries the centre of the global spice trade, the Maluku Islands were the only source of cloves until the 18th century. Clove oil has been used as an analgesic and antiseptic in traditional medicine worldwide since antiquity — including as a dental anaesthetic.',
    description: 'One of the most powerful and potentially irritating essential oils due to its very high eugenol content (up to 95%). It has exceptional antiseptic and warming analgesic properties, but must be used at very low dilutions and avoided on sensitive skin.',
    benefits: ['Powerful antiseptic and antimicrobial', 'Strong analgesic for muscle and joint pain', 'Warming and stimulating to circulation', 'Anti-inflammatory', 'Traditionally used for dental and topical pain'],
    contraindications: ['Maximum 0.5% dilution — high dermal sensitisation risk', 'Avoid on sensitive, damaged, or inflamed skin', 'Avoid in pregnancy', 'Blood thinner — avoid with anticoagulant medications', 'Never use undiluted'],
    aroma: 'warm, spicy, sweet, medicinal',
    dilutionRateMax: 0.005,
  },
  {
    name: 'Ginger',
    botanicalName: 'Zingiber officinale',
    origin: 'Southeast Asia, India',
    history: 'Ginger has been cultivated for at least 5,000 years in South Asia and was among the first spices to reach Europe. Ancient Indian, Chinese, and Greek physicians all recorded its therapeutic uses, particularly for digestive and circulatory conditions.',
    description: 'A warming, stimulating oil with excellent anti-nausea and circulatory properties. In massage, it is particularly effective for cold, stiff muscles, poor circulation, arthritic joints, and as a warming pre-sports treatment. Best used fresh-distilled to maximise its zingerone content.',
    benefits: ['Powerfully warming to circulation', 'Anti-nausea and digestive support', 'Analgesic for arthritic and cold joints', 'Emotionally warming and confidence-building', 'Stimulates and decongests'],
    contraindications: ['Potential skin irritant — patch test recommended', 'Avoid on inflamed or sensitive skin', 'Avoid with blood-thinning medications'],
    aroma: 'warm, spicy, earthy, slightly sweet',
    dilutionRateMax: 0.02,
  },
  {
    name: 'Black Pepper',
    botanicalName: 'Piper nigrum',
    origin: 'Kerala, India',
    history: 'Once so valuable it was used as currency, black pepper has been traded from India to Rome, Arabia, and China for over 4,000 years. Medieval spice routes were built around it. Beyond culinary use, it features prominently in Ayurvedic medicine as a circulatory stimulant and digestive aid.',
    description: 'A warming, stimulating oil with a dry, spicy character very different from culinary black pepper. In massage, it is primarily used as a circulatory stimulant and for warming blends, especially effective for cold muscles, poor circulation, and motivation-focused treatments.',
    benefits: ['Warming circulatory stimulant', 'Analgesic for muscular aches', 'Emotionally warming and motivating', 'Improves digestive function', 'Supports detoxification massage'],
    contraindications: ['Use at low dilution — can be irritating in high amounts', 'Avoid with kidney disease', 'Patch test for sensitive skin'],
    aroma: 'dry, warm, spicy, woody',
    dilutionRateMax: 0.03,
  },
  {
    name: 'Vetiver',
    botanicalName: 'Chrysopogon zizanioides (Vetiveria zizanioides)',
    origin: 'India, Haiti, Réunion',
    history: 'Known as the "oil of tranquility" in India and Sri Lanka, vetiver has been used in South Asian traditions for centuries as a cooling, grounding, and protective herb. The roots were woven into door and window screens so that water could be poured over them in summer heat, releasing the cooling aroma.',
    description: 'One of the most deeply grounding and tenacious essential oils, vetiver acts as a base note and fixative in blends. Its thick, smoky, earthy aroma is complex and improves with age. In massage, it is particularly effective for nervous exhaustion, anxiety, and providing emotional grounding.',
    benefits: ['Deeply grounding and stabilising', 'Helps anxiety and nervous exhaustion', 'Fixative — holds blend together', 'Anti-inflammatory for skin', 'Cooling in Ayurvedic tradition'],
    contraindications: ['Very thick — use at 1–2% maximum', 'Strong aroma — use sparingly'],
    aroma: 'deep, smoky, earthy, woody, complex',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Sandalwood',
    botanicalName: 'Santalum album (Indian) / Santalum spicatum (Australian)',
    origin: 'India (Mysore), Australia',
    history: 'Sandalwood has been used in religious and therapeutic practice in India for over 4,000 years, integral to Hindu, Buddhist, and Ayurvedic traditions. Mysore sandalwood from Karnataka was once the gold standard and is now protected due to over-harvesting. Australian sandalwood is now the sustainable alternative.',
    description: 'A warm, creamy, woody oil with remarkable fixative properties and documented anti-inflammatory action. It is one of the most effective oils for dry, ageing, or dehydrated skin and provides a meditative, calming anchor in complex blends. Blends with virtually everything.',
    benefits: ['Deeply moisturising for dry and ageing skin', 'Calming and meditative', 'Excellent fixative in complex blends', 'Anti-inflammatory skin properties', 'Aphrodisiac and grounding'],
    contraindications: ['Ensure sustainable sourcing (Australian is preferred)'],
    aroma: 'warm, creamy, woody, milky, sweet',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Cedarwood',
    botanicalName: 'Cedrus atlantica (Atlas) / Juniperus virginiana (Virginian)',
    origin: 'Morocco (Atlas), USA (Virginian)',
    history: 'One of the oldest used aromatics, cedarwood resin was used by the ancient Egyptians for embalming and by Mesopotamian civilisations in temple rituals. Atlas cedarwood from Morocco is distilled from the Atlas Mountains and is considered the superior therapeutic variety.',
    description: 'A warm, woody, slightly sweet oil with calming and grounding properties. Particularly effective for respiratory support, dry skin and scalp conditions, and emotional grounding in massage. Atlas cedarwood is preferred over Virginian for therapeutic use.',
    benefits: ['Grounding and calming', 'Supports respiratory function', 'Beneficial for dry skin and dandruff', 'Mild astringent for oily skin', 'Emotionally stabilising'],
    contraindications: ['Avoid in pregnancy', 'Ensure Atlas variety for therapeutic use'],
    aroma: 'warm, woody, sweet, pencil-shavings',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Jasmine Absolute',
    botanicalName: 'Jasminum grandiflorum / Jasminum officinale',
    origin: 'Egypt, India, France',
    history: 'Known as the "king of flowers" in contrast to rose\'s "queen," jasmine has been central to perfumery and ceremonial practice across Asia, the Middle East, and Mediterranean cultures for thousands of years. Indian jasmine cultivation for religious and aromatic use predates recorded history.',
    description: 'A rich, intensely floral absolute (not a steam-distilled oil) with one of the most complex aromatic profiles in perfumery. It has documented euphoric and antidepressant properties and is traditionally considered an aphrodisiac. Due to high cost, it is used in small proportions.',
    benefits: ['Antidepressant and euphoric', 'Deeply calming for anxiety and depression', 'Traditionally used as aphrodisiac', 'Warming and confidence-building', 'Valuable in grief and emotional release work'],
    contraindications: ['Avoid in pregnancy', 'Use at very low dilution (0.5–1%) due to intensity and cost', 'Solvent-residue concern — check for CO2 or enfleurage sourcing for sensitive skin'],
    aroma: 'intensely floral, sweet, exotic, rich',
    dilutionRateMax: 0.02,
  },
  {
    name: 'Rose Otto',
    botanicalName: 'Rosa damascena',
    origin: 'Bulgaria (Valley of Roses), Turkey, Morocco',
    history: 'The "queen of essential oils," rose otto requires approximately 4 tonnes of petals to produce one litre of oil, making it among the most expensive in the world. Bulgarian rose cultivation in the Kazanlak valley has continued since the Ottoman period, and the harvest is still a celebrated cultural event.',
    description: 'Steam-distilled from Rosa damascena petals, true rose otto is an emotionally profound oil associated with the heart, self-love, and grief. Its complex chemistry includes geraniol, citronellol, and the unique rose oxide. It is used at low dilutions and is among the most therapeutically potent of all essential oils for emotional work.',
    benefits: ['Profound effect on emotional wellbeing', 'Supports grief, loss, and heartbreak', 'Anti-inflammatory for skin', 'Aphrodisiac properties', 'Promotes feelings of self-worth and love'],
    contraindications: ['Avoid in first trimester (mild uterine stimulant)', 'Ensure otto (steam-distilled) not absolute for massage', 'Very expensive — often adulterated, ensure quality source'],
    aroma: 'rich, deep, floral, honeyed, complex',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Sweet Marjoram',
    botanicalName: 'Origanum majorana',
    origin: 'Mediterranean, Egypt',
    history: 'In ancient Greece, marjoram was associated with Aphrodite and was traditionally placed on graves as a symbol of happiness in the afterlife. Medieval European herbalists used it extensively for both culinary and medicinal purposes, particularly for warming cold, stiff conditions.',
    description: 'A warm, comforting oil with powerful antispasmodic and analgesic properties particularly effective for muscle spasm, tension headaches, and menstrual cramps. It is deeply warming and sedating, making it valuable for cold, stiff conditions and anxiety-related muscular tension.',
    benefits: ['Powerful antispasmodic for muscle cramps', 'Analgesic for tension and headaches', 'Deeply warming and comforting', 'Lowers blood pressure', 'Helpful for insomnia and anxiety'],
    contraindications: ['Avoid in pregnancy', 'May lower blood pressure — use carefully with medication', 'Sedating — avoid before driving'],
    aroma: 'warm, herbaceous, slightly spicy, woody',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Helichrysum',
    botanicalName: 'Helichrysum italicum',
    origin: 'Mediterranean — Corsica, Croatia, Italy',
    history: 'Known as "everlasting" or "immortelle" due to its dried flowers retaining colour indefinitely, helichrysum has a long tradition in Mediterranean and North African folk medicine for skin healing and wound care. Corsican helichrysum is considered the most therapeutically active variety.',
    description: 'One of the most powerful and unique essential oils for tissue repair and bruising. Its distinctive chemistry — including neryl acetate and italidiones — makes it highly effective for haematomas, scar tissue, and inflammation. It is a premium oil used in small quantities.',
    benefits: ['Exceptional tissue repair and anti-bruising', 'Reduces scar tissue and haematomas', 'Powerful anti-inflammatory', 'Promotes cellular regeneration', 'Supports post-injury recovery'],
    contraindications: ['Expensive premium oil — typically used at 0.5–1%', 'Avoid with blood-thinning medications'],
    aroma: 'earthy, honey-like, herbal, curry-like',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Neroli',
    botanicalName: 'Citrus aurantium var. amara (blossoms)',
    origin: 'Tunisia, Morocco, Egypt, Italy',
    history: 'Named after Anna Maria de la Trémoille, Princess of Nerola, who popularised the oil in 17th century Italy, neroli is distilled from bitter orange blossoms. Traditionally associated with weddings in Mediterranean cultures, it was used in bridal bouquets for its ability to ease bridal nerves.',
    description: 'A precious, complex floral oil distilled from bitter orange blossoms with profound calming and antidepressant effects. It has a unique ability to ease acute anxiety and panic, and is particularly associated with nervous palpitations, shock, and emotional trauma in clinical aromatherapy.',
    benefits: ['Powerful calming for acute anxiety', 'Helps with panic, shock, and grief', 'Antidepressant', 'Supports skin regeneration', 'Uplifting and deeply calming simultaneously'],
    contraindications: ['Expensive — typically used at 0.5–1%', 'Avoid confusing with petitgrain or bitter orange leaf'],
    aroma: 'rich floral, citrus, green, honeyed',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Cypress',
    botanicalName: 'Cupressus sempervirens',
    origin: 'Mediterranean — France, Spain, Morocco',
    history: 'Sacred to the ancients Greeks and Romans who planted cypress trees in cemeteries as symbols of immortality, cypress has been used medicinally throughout the Mediterranean for millennia. Ancient Egyptian physicians prescribed it for liver conditions and Hippocrates referenced it for haemorrhoids.',
    description: 'A clean, woody, slightly astringent oil with excellent circulation-supporting properties. It is one of the most valuable oils in massage for varicose veins, fluid retention, heavy legs, and lymphatic drainage work. Its astringent properties also make it effective for excessive perspiration.',
    benefits: ['Supports venous circulation and varicose veins', 'Valuable in lymphatic drainage massage', 'Reduces fluid retention', 'Astringent for oily skin', 'Grounding and fortifying emotionally'],
    contraindications: ['Avoid in pregnancy', 'Avoid with hormone-sensitive conditions', 'Avoid with clotting disorders'],
    aroma: 'clean, woody, fresh, slightly camphoraceous',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Juniper Berry',
    botanicalName: 'Juniperus communis',
    origin: 'France, Canada, Italy',
    history: 'Used by indigenous peoples across the Northern Hemisphere, juniper berries have been found in Egyptian tombs dated to 1500 BCE. The plant has strong purification symbolism across Tibetan, Native American, and European traditions, and gin\'s distinctive flavour derives from its berries.',
    description: 'A sharp, woody, slightly spicy oil with strong diuretic, detoxifying, and purifying properties. Particularly valuable in detoxification massage, treatment of cellulite, and joint conditions including gout and arthritis. Should be used from berry distillation (not needle) for maximum purity.',
    benefits: ['Detoxifying and diuretic', 'Supports treatment of cellulite', 'Anti-inflammatory for gout and arthritis', 'Purifying and protective', 'Supports lymphatic detoxification'],
    contraindications: ['Avoid in pregnancy', 'Avoid with kidney disease or kidney infection', 'Kidney-stimulating — not for long-term use'],
    aroma: 'sharp, woody, spicy, fresh',
    dilutionRateMax: 0.03,
  },
  {
    name: 'Patchouli',
    botanicalName: 'Pogostemon cablin',
    origin: 'Indonesia, India, Philippines',
    history: 'Used in India and Malaysia for centuries to repel insects from stored fabrics and to scent textiles traded along the Silk Road, patchouli was a signifier of authentic Indian goods. The oil became synonymous with the 1960s counterculture movement and remains one of the most recognisable perfumery materials.',
    description: 'A deep, complex, earthy base note oil that improves significantly with age. It has grounding, anti-inflammatory, and antifungal properties and is one of the best skin-regenerating essential oils. Its exceptionally complex aroma makes it both a therapeutic tool and a perfumery anchor.',
    benefits: ['Deeply grounding and earthy', 'Anti-inflammatory and antifungal', 'Excellent for skin regeneration and scarring', 'Fixative for complex blends', 'Aphrodisiac properties'],
    contraindications: ['Very strong — use sparingly at 1–2%', 'Some people find the aroma challenging'],
    aroma: 'deep, earthy, musky, sweet, complex',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Cardamom',
    botanicalName: 'Elettaria cardamomum',
    origin: 'Southern India, Guatemala',
    history: 'Among the oldest known spices, cardamom was used in ancient Ayurvedic medicine and has been traded from India to Europe since at least 700 BCE. Ancient Egyptians used it for purification rituals and teeth-chewing. Vikings brought it to Scandinavia where it remains culturally embedded in cuisine today.',
    description: 'A warm, sweet, spicy oil with excellent digestive and respiratory properties. In massage, it provides gentle warming and is particularly effective for digestive massage, respiratory conditions, and as a warming complement to cooling or floral blends. Its aroma is universally appealing.',
    benefits: ['Digestive support and anti-nausea', 'Gently warming to circulation', 'Mentally stimulating and clarity-promoting', 'Aphrodisiac properties', 'Expectorant for respiratory support'],
    contraindications: ['Avoid with known spice sensitisation'],
    aroma: 'warm, sweet, spicy, slightly camphoraceous',
    dilutionRateMax: 0.03,
  },
  {
    name: 'Copaiba',
    botanicalName: 'Copaifera officinalis / Copaifera reticulata',
    origin: 'Brazil, Colombia, Venezuela',
    history: 'The indigenous peoples of Amazonia have used copaiba resin for thousands of years as a wound healer, anti-inflammatory, and respiratory remedy. Brazilian folk medicine has long used it for inflammatory conditions. Modern research has focused on its beta-caryophyllene content and its interaction with the endocannabinoid system.',
    description: 'A powerful but gentle anti-inflammatory oil rich in beta-caryophyllene (BCP), a sesquiterpene that activates CB2 receptors in the endocannabinoid system without psychoactive effects. It amplifies the effects of other oils and is particularly effective for chronic pain and inflammation.',
    benefits: ['Powerful anti-inflammatory (beta-caryophyllene)', 'Amplifies and synergises with other essential oils', 'Supports the endocannabinoid system', 'Wound healing and antimicrobial', 'Very low sensitisation risk'],
    contraindications: ['Avoid with blood-thinning medications'],
    aroma: 'mild, balsamic, woody, sweet',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Ho Wood',
    botanicalName: 'Cinnamomum camphora ct. linalool',
    origin: 'China, Taiwan',
    history: 'Ho Wood is the sustainable alternative to rosewood (Aniba rosaeodora), distilled from the leaves and branches of the Cinnamomum camphora tree. It was developed in response to conservation concerns about Brazilian rosewood and has largely replaced it in aromatherapy since the 2000s.',
    description: 'Exceptionally high in linalool (80–99%), Ho Wood is one of the gentlest and most therapeutically reliable essential oils. Its calming, anti-inflammatory properties make it suitable for sensitive skin, and it is an excellent substitute for rosewood or lavender in many applications.',
    benefits: ['Extremely high linalool content — calming', 'Gentle and suitable for sensitive skin', 'Sustainable rosewood alternative', 'Anti-inflammatory and analgesic', 'Antifungal and antimicrobial'],
    contraindications: ['Extremely safe — very few contraindications'],
    aroma: 'fresh, floral, woody, sweet, rose-like',
    dilutionRateMax: 0.05,
  },
  {
    name: 'Spearmint',
    botanicalName: 'Mentha spicata',
    origin: 'Mediterranean, introduced globally',
    history: 'The older and gentler sibling of peppermint, spearmint has been used medicinally since ancient Greece. It was used extensively by the Romans who brought it throughout the Roman Empire. Spearmint contains carvone rather than menthol, giving it a sweeter, less intense character.',
    description: 'A gentler, sweeter alternative to peppermint with similar cooling and digestive properties but without the intensity of menthol. It is suitable for use with children (unlike peppermint), provides mild cooling for massage, and is a valuable companion in digestive and refreshing blends.',
    benefits: ['Gentler cooling alternative to peppermint', 'Digestive support and anti-nausea', 'Safe for children over 6 in appropriate dilution', 'Refreshing and mentally stimulating', 'Antimicrobial properties'],
    contraindications: ['Avoid in large quantities with epilepsy', 'Avoid in first trimester'],
    aroma: 'sweet, fresh, slightly minty, lighter than peppermint',
    dilutionRateMax: 0.04,
  },
]

// ─── Notable Pairings ─────────────────────────────────────────────────────────
// Only EXCELLENT / CAUTION / AVOID defined here.
// All unlisted pairs default to GOOD (compatible, no concerns) in the app.

const NOTABLE_PAIRINGS: Array<{
  a: string
  b: string
  rating: 'EXCELLENT' | 'CAUTION' | 'AVOID'
  reason: string
}> = [
  // ── EXCELLENT: Classic therapeutic combos ──────────────────────────────────
  { a: 'Lavender', b: 'Frankincense', rating: 'EXCELLENT', reason: 'One of aromatherapy\'s most celebrated pairings — lavender lifts the spirit while frankincense grounds and deepens the breath, creating a profoundly relaxing blend.' },
  { a: 'Lavender', b: 'Roman Chamomile', rating: 'EXCELLENT', reason: 'Both are powerfully calming anti-inflammatories; together they create an exceptional blend for anxiety, tension, and sleep.' },
  { a: 'Lavender', b: 'Bergamot', rating: 'EXCELLENT', reason: 'Bergamot\'s uplifting qualities balance lavender\'s calming nature, creating a mood-elevating yet relaxing blend for stress and mild depression.' },
  { a: 'Lavender', b: 'Cedarwood', rating: 'EXCELLENT', reason: 'The herbaceous freshness of lavender and the warm woodiness of cedarwood complement each other beautifully for sleep and relaxation blends.' },
  { a: 'Lavender', b: 'Vetiver', rating: 'EXCELLENT', reason: 'Lavender\'s gentle floral quality lifts vetiver\'s deep earthiness to create a grounding, calming blend for anxiety and nervous exhaustion.' },
  { a: 'Lavender', b: 'Sweet Marjoram', rating: 'EXCELLENT', reason: 'Both are warming antispasmodics; together they create a powerful blend for muscle tension, cramps, and stress-related pain.' },
  { a: 'Lavender', b: 'Sandalwood', rating: 'EXCELLENT', reason: 'Sandalwood\'s creamy warmth and lavender\'s floral delicacy create a deeply calming, skin-nourishing combination ideal for relaxation massage.' },
  { a: 'Lavender', b: 'Neroli', rating: 'EXCELLENT', reason: 'Both work on anxiety and nervous tension through different mechanisms; together they create a deeply reassuring blend for emotional stress.' },
  { a: 'Lavender', b: 'Ho Wood', rating: 'EXCELLENT', reason: 'Both are high in linalool; their combined calming, anti-inflammatory properties are magnified while the aromas complement each other beautifully.' },
  { a: 'Lavender', b: 'Jojoba', rating: 'EXCELLENT', reason: 'Jojoba\'s neutral, sebum-like quality is the ideal carrier for lavender\'s versatile chemistry — a classic combination for all-purpose massage.' },
  { a: 'Lavender', b: 'Sweet Almond', rating: 'EXCELLENT', reason: 'The quintessential massage combination — sweet almond\'s slip and lavender\'s calming properties create the archetypal relaxation massage blend.' },
  { a: 'Frankincense', b: 'Sandalwood', rating: 'EXCELLENT', reason: 'Both sacred woods with meditative traditions; together they create a profoundly grounding, spiritually resonant blend for deep relaxation.' },
  { a: 'Frankincense', b: 'Cedarwood', rating: 'EXCELLENT', reason: 'The balsamic depth of frankincense and the warm woodiness of cedarwood create a grounding, warming combination with powerful anti-inflammatory properties.' },
  { a: 'Frankincense', b: 'Rose Otto', rating: 'EXCELLENT', reason: 'A luxury pairing for skin regeneration and emotional healing — frankincense\'s cellular support combined with rose\'s heart-opening properties.' },
  { a: 'Frankincense', b: 'Rosehip Seed', rating: 'EXCELLENT', reason: 'Rosehip\'s vitamin A and frankincense\'s boswellic acids work synergistically for skin regeneration — one of the best pairings for anti-ageing blends.' },
  { a: 'Bergamot', b: 'Neroli', rating: 'EXCELLENT', reason: 'Two citrus flowers from the same family (Citrus aurantium); they share chemical constituents and create a seamlessly uplifting, anxiety-relieving blend.' },
  { a: 'Bergamot', b: 'Geranium', rating: 'EXCELLENT', reason: 'Bergamot\'s bright citrus note and geranium\'s rose-green quality balance perfectly for mood, hormonal support, and antidepressant blends.' },
  { a: 'Rose Otto', b: 'Geranium', rating: 'EXCELLENT', reason: 'Geranium is the natural companion to rose — sharing geraniol chemistry, they enhance each other\'s floral character while geranium extends the costly rose.' },
  { a: 'Rose Otto', b: 'Sandalwood', rating: 'EXCELLENT', reason: 'One of perfumery\'s classic oriental combinations; sandalwood\'s creamy fixative quality enhances rose\'s longevity and creates a deeply romantic blend.' },
  { a: 'Rose Otto', b: 'Argan', rating: 'EXCELLENT', reason: 'Argan\'s vitamin E richness and rose\'s skin regeneration properties create an exceptionally nourishing luxury blend for mature or stressed skin.' },
  { a: 'Rosemary', b: 'Peppermint', rating: 'EXCELLENT', reason: 'Both are stimulating and circulation-enhancing; together they create an energising, muscle-warming blend ideal for sports preparation.' },
  { a: 'Ginger', b: 'Black Pepper', rating: 'EXCELLENT', reason: 'Two warming circulatory stimulants that complement each other perfectly for deep warming, circulation-boosting, and pre-sports massage.' },
  { a: 'Ginger', b: 'Sweet Marjoram', rating: 'EXCELLENT', reason: 'Ginger\'s warming circulatory action combined with marjoram\'s antispasmodic properties make an excellent blend for cold, stiff, or arthritic conditions.' },
  { a: 'Cedarwood', b: 'Vetiver', rating: 'EXCELLENT', reason: 'Both are deeply grounding base notes — cedar brings freshness to vetiver\'s depth, creating a stabilising, earthy blend for anxiety and stress.' },
  { a: 'Patchouli', b: 'Sandalwood', rating: 'EXCELLENT', reason: 'Patchouli\'s earthy complexity and sandalwood\'s creamy warmth create a deep, sensual, grounding blend that improves with skin contact.' },
  { a: 'Patchouli', b: 'Ylang Ylang', rating: 'EXCELLENT', reason: 'An exotic, sensual pairing used in perfumery and romantic massage — patchouli grounds ylang ylang\'s heady sweetness into a balanced, aphrodisiac blend.' },
  { a: 'Helichrysum', b: 'Frankincense', rating: 'EXCELLENT', reason: 'Both are exceptional skin regenerators with different mechanisms — helichrysum\'s haematoma action plus frankincense\'s cellular repair creates a powerful recovery blend.' },
  { a: 'Helichrysum', b: 'Rosehip Seed', rating: 'EXCELLENT', reason: 'Together, these form the most potent skin repair pairing in aromatherapy — helichrysum for bruising and scar tissue, rosehip for regeneration and hyperpigmentation.' },
  { a: 'Marula', b: 'Sandalwood', rating: 'EXCELLENT', reason: 'Marula\'s silky, rapidly absorbing base complements sandalwood\'s meditative quality; together they create a luxury facial and body treatment.' },
  { a: 'Pomegranate Seed', b: 'Frankincense', rating: 'EXCELLENT', reason: 'A premium anti-ageing pairing — pomegranate\'s punicic acid and frankincense\'s boswellic acids work synergistically on skin renewal.' },
  { a: 'Fractionated Coconut', b: 'Peppermint', rating: 'EXCELLENT', reason: 'Fractionated coconut\'s neutral, lightweight glide is the ideal carrier for peppermint\'s cooling, analgesic properties in sports massage.' },
  { a: 'Hemp Seed', b: 'Black Pepper', rating: 'EXCELLENT', reason: 'Hemp seed\'s anti-inflammatory fatty acid profile and black pepper\'s warming circulatory properties create an exceptional blend for joint and circulation massage.' },
  { a: 'Evening Primrose', b: 'Rose Otto', rating: 'EXCELLENT', reason: 'Evening primrose\'s GLA-rich anti-inflammatory base and rose\'s skin-supporting chemistry create a deeply therapeutic blend for hormonal or sensitive skin.' },
  { a: 'Copaiba', b: 'Frankincense', rating: 'EXCELLENT', reason: 'Copaiba amplifies frankincense\'s anti-inflammatory action through its beta-caryophyllene content — one of the most potent anti-inflammatory pairings available.' },
  { a: 'Copaiba', b: 'Lavender', rating: 'EXCELLENT', reason: 'Copaiba\'s synergistic properties amplify lavender\'s calming and analgesic effects; this pairing is valued in clinical aromatherapy for pain management.' },
  { a: 'Cypress', b: 'Geranium', rating: 'EXCELLENT', reason: 'Both support circulation and lymphatic function — a classic pairing for lymphatic drainage massage and treatment of fluid retention.' },
  { a: 'Juniper Berry', b: 'Cypress', rating: 'EXCELLENT', reason: 'Both are exceptional for detoxification and lymphatic drainage; their combined diuretic and circulation-supporting properties enhance detox massage.' },
  { a: 'Spearmint', b: 'Lavender', rating: 'EXCELLENT', reason: 'Spearmint\'s gentle cooling freshness pairs beautifully with lavender\'s calming properties, creating an approachable, balanced blend suitable for most people.' },
  { a: 'Cardamom', b: 'Ginger', rating: 'EXCELLENT', reason: 'Two warming spices from the same family — cardamom\'s sweet complexity refines ginger\'s intensity, creating an appealing, warming digestive and circulatory blend.' },

  // ── CAUTION pairings ──────────────────────────────────────────────────────────
  { a: 'Clove Bud', b: 'Black Pepper', rating: 'CAUTION', reason: 'Two intensely warming and potentially irritating oils; combined at standard dilutions, the cumulative dermal load of eugenol and piperine can cause significant skin irritation.' },
  { a: 'Clove Bud', b: 'Ginger', rating: 'CAUTION', reason: 'Both are intense warming and potentially irritating oils. Combined, their cumulative heating action can exceed safe dermal levels — keep total clove bud under 0.5% in any blend.' },
  { a: 'Clove Bud', b: 'Lemongrass', rating: 'CAUTION', reason: 'Eugenol (clove) and citral (lemongrass) together increase sensitisation risk significantly. Avoid on sensitive skin; patch test essential.' },
  { a: 'Ylang Ylang', b: 'Jasmine Absolute', rating: 'CAUTION', reason: 'Both are intensely heady, heavy florals that can cause headaches and nausea when combined at higher dilutions. Keep total concentration under 1% and ensure good ventilation.' },
  { a: 'Rosemary', b: 'Clary Sage', rating: 'CAUTION', reason: 'Both are stimulating and have ketone content. Combined they can be overstimulating for the nervous system; avoid in pregnancy and epilepsy, and do not use before sleep.' },
  { a: 'Peppermint', b: 'Spearmint', rating: 'CAUTION', reason: 'Both contain menthol-family compounds; combining them at full dilution creates a cumulative mint intensity that can be overwhelming and cause tingling or irritation on sensitive skin.' },
  { a: 'Eucalyptus', b: 'Rosemary', rating: 'CAUTION', reason: 'Both are high in cineole and camphor-type compounds; combined they can be overstimulating for the central nervous system, particularly for those with epilepsy or high blood pressure.' },
  { a: 'Lemongrass', b: 'Bergamot', rating: 'CAUTION', reason: 'Both contain significant citral/furocoumarin content; combined they increase phototoxicity risk if used before UV exposure. Use only FCF bergamot in this combination.' },
  { a: 'Castor', b: 'Ginger', rating: 'CAUTION', reason: 'Castor\'s occlusive nature significantly intensifies essential oil skin absorption; ginger\'s potential for irritation is amplified. Use at half the normal ginger dilution in this carrier.' },
  { a: 'Castor', b: 'Lemongrass', rating: 'CAUTION', reason: 'Castor\'s occlusive properties intensify lemongrass absorption; lemongrass\'s sensitisation potential is increased. Lower lemongrass to 1% maximum in castor-containing blends.' },
  { a: 'Castor', b: 'Black Pepper', rating: 'CAUTION', reason: 'Castor\'s slow, occlusive absorption amplifies black pepper\'s warming and potential irritation; reduce black pepper to 1% maximum when using castor as a carrier.' },
  { a: 'Avocado', b: 'Clove Bud', rating: 'CAUTION', reason: 'Avocado\'s heavy, penetrating nature can amplify clove bud\'s already high sensitisation potential. Keep clove bud to an absolute maximum of 0.25% in avocado-containing blends.' },
  { a: 'Clary Sage', b: 'Ylang Ylang', rating: 'CAUTION', reason: 'Both have sedative and blood pressure-lowering effects; combined they can cause excessive hypotension and dizziness. Use at lower combined dilutions and monitor response.' },
  { a: 'Black Pepper', b: 'Lemongrass', rating: 'CAUTION', reason: 'Both are warming and potentially sensitising; combined they increase the risk of skin irritation, particularly on sensitive or recently exfoliated skin.' },

  // ── AVOID pairings ──────────────────────────────────────────────────────────
  { a: 'Clove Bud', b: 'Bergamot', rating: 'AVOID', reason: 'Eugenol from clove bud combined with furanocoumarins in non-FCF bergamot creates a high phototoxicity and sensitisation risk. Even with FCF bergamot, the combination is not recommended for most skin types.' },
  { a: 'Ylang Ylang', b: 'Peppermint', rating: 'AVOID', reason: 'A serious therapeutic mismatch — ylang ylang is deeply sedating and hypotensive while peppermint is stimulating and cooling. Their competing effects can cause disorientation and headaches.' },
  { a: 'Clary Sage', b: 'Peppermint', rating: 'AVOID', reason: 'These oils have directly opposing actions — clary sage is deeply sedating, euphoriant, and hypotensive, while peppermint is stimulating and hypertensive. Do not combine in massage.' },
  { a: 'Rosemary', b: 'Ylang Ylang', rating: 'AVOID', reason: 'Rosemary is a central nervous system stimulant while ylang ylang is a profound CNS depressant. Their opposing pharmacological actions create unpredictable effects.' },

  // ── New carrier oils — EXCELLENT pairings ────────────────────────────────
  { a: 'Calendula', b: 'Lavender', rating: 'EXCELLENT', reason: "Calendula's carotenoid-rich anti-inflammatory base and lavender's calming skin chemistry create one of the gentlest and most broadly useful pairings — ideal for sensitive skin, children's massage, or post-procedure care." },
  { a: 'Calendula', b: 'Roman Chamomile', rating: 'EXCELLENT', reason: 'Both are anti-inflammatory powerhouses from the same botanical family. Together they create an exceptionally soothing blend for eczema, dermatitis, irritated skin, and stress-related inflammatory conditions.' },
  { a: 'Calendula', b: 'Helichrysum', rating: 'EXCELLENT', reason: "Calendula's skin-repair flavonoids and helichrysum's italidione chemistry work synergistically for wound healing, scar treatment, and post-injury skin recovery." },
  { a: "St John's Wort", b: 'Lavender', rating: 'EXCELLENT', reason: "St John's Wort's antineuralgic hypericin and lavender's analgesic and anti-inflammatory properties combine into an outstanding blend for nerve pain, sciatica, and tension-related discomfort." },
  { a: "St John's Wort", b: 'Helichrysum', rating: 'EXCELLENT', reason: "A premium nerve and tissue recovery pairing — helichrysum's sesquiterpene lactones for tissue repair and St John's Wort's antineuralgic action for nerve pain create a powerful post-injury treatment." },
  { a: "St John's Wort", b: 'Frankincense', rating: 'EXCELLENT', reason: "St John's Wort's anti-inflammatory infused base and frankincense's boswellic acids create a deeply therapeutic blend for chronic inflammation, joint pain, and nerve-adjacent muscular conditions." },
  { a: 'Arnica', b: 'Helichrysum', rating: 'EXCELLENT', reason: "Two of the most powerful anti-bruising agents in aromatherapy — arnica's helenalin compounds and helichrysum's italidiones work through complementary pathways to create an unmatched blend for haematomas, sports injuries, and post-trauma tissue." },
  { a: 'Arnica', b: 'Black Pepper', rating: 'EXCELLENT', reason: "Arnica's tissue anti-inflammatory properties paired with black pepper's circulation-stimulating warmth create an excellent pre- and post-sports blend — preparation and recovery in one combination." },
  { a: 'Arnica', b: 'Ginger', rating: 'EXCELLENT', reason: "Arnica's anti-inflammatory infused base and ginger's warming circulatory stimulation create a potent blend for cold, injured, or stiff musculoskeletal conditions and sports recovery." },
  { a: 'Arnica', b: 'Sweet Marjoram', rating: 'EXCELLENT', reason: "Arnica's injury-focused anti-inflammatory carrier and marjoram's antispasmodic action pair excellently for muscle spasm, post-strain stiffness, and sports rehabilitation massage." },
  { a: 'Comfrey', b: 'Helichrysum', rating: 'EXCELLENT', reason: "Comfrey's allantoin cell-proliferation action and helichrysum's scar-reducing italidiones work by different mechanisms on the same goal — tissue restoration and recovery after injury." },
  { a: 'Comfrey', b: 'Sweet Marjoram', rating: 'EXCELLENT', reason: "Comfrey's allantoin-rich tissue repair base and marjoram's antispasmodic warmth create an ideal blend for musculoskeletal injuries, sprains, and muscle strain recovery." },
  { a: 'Comfrey', b: 'Frankincense', rating: 'EXCELLENT', reason: "Comfrey's allantoin promotes cell proliferation while frankincense's boswellic acids reduce inflammation — a complementary pairing for ligament and soft tissue injury recovery." },
  { a: 'Neem', b: 'Tea Tree', rating: 'EXCELLENT', reason: "The most powerful antimicrobial and antifungal pairing in the oil toolkit — neem's broad-spectrum activity and tea tree's documented antimicrobial action combine for serious skin infections and chronic fungal conditions. Always blend with a neutral carrier." },
  { a: 'Neem', b: 'Lavender', rating: 'EXCELLENT', reason: "Lavender's anti-inflammatory and skin-soothing properties help moderate neem's intensity while contributing therapeutically — a classic pairing for scalp conditions, dandruff, and eczema where neem's odour must be softened." },
  { a: 'Wheat Germ', b: 'Rosehip Seed', rating: 'EXCELLENT', reason: "Wheat germ's tocopherol (vitamin E) stabilises and extends rosehip's easily-oxidised linoleic content, while both contribute powerfully to skin regeneration — a synergistic anti-ageing and scar-treatment pairing." },
  { a: 'Wheat Germ', b: 'Frankincense', rating: 'EXCELLENT', reason: "Adding wheat germ at 10% to a frankincense blend provides powerful antioxidant protection that extends the blend's shelf life and contributes complementary vitamin E skin-renewal action." },
  { a: 'Borage Seed', b: 'Evening Primrose', rating: 'EXCELLENT', reason: "Both are prized for their exceptional GLA content — blending them creates the highest combined GLA concentration available from plant sources, creating a potent therapeutic carrier for eczema, hormonal skin, and inflammatory conditions." },
  { a: 'Borage Seed', b: 'Rose Otto', rating: 'EXCELLENT', reason: "Borage seed's high GLA anti-inflammatory content and rose's profound skin-supportive chemistry create a luxury hormonal and skin-regenerating pairing particularly suited to menopausal and mature skin." },
  { a: 'Borage Seed', b: 'Geranium', rating: 'EXCELLENT', reason: "Borage seed's GLA content and geranium's hormonal-balancing properties work synergistically for skin conditions with hormonal drivers — a complementary pairing for hormonally reactive skin." },
  { a: 'Macadamia', b: 'Frankincense', rating: 'EXCELLENT', reason: "Macadamia's palmitoleic acid replenishes age-declining skin lipids while frankincense's boswellic acids reduce inflammation and support cellular regeneration — an outstanding combination for mature skin treatment." },
  { a: 'Macadamia', b: 'Sandalwood', rating: 'EXCELLENT', reason: "Macadamia's silky skin-compatible base and sandalwood's meditative, moisturising quality create a luxury calming blend with exceptional skin compatibility — ideal for facial and body massage." },
  { a: 'Macadamia', b: 'Rose Otto', rating: 'EXCELLENT', reason: "A premium anti-ageing luxury pairing — macadamia's palmitoleic acid compatibility with mature skin and rose otto's profound skin and emotional properties create an exceptional treatment blend." },
  { a: 'Walnut', b: 'Rosemary', rating: 'EXCELLENT', reason: "Walnut oil's omega-3 anti-inflammatory base and rosemary's circulation-stimulating, antifungal properties combine well for scalp treatments and massage blends for dry, inflamed, or flaking scalp conditions." },
  { a: 'Olive', b: 'Lavender', rating: 'EXCELLENT', reason: "The oldest recorded therapeutic combination in Western aromatherapy — ancient Mediterranean physicians used olive oil infused with lavender for skin and muscle care. A historically and therapeutically significant pairing." },
  { a: 'Olive', b: 'Frankincense', rating: 'EXCELLENT', reason: "A sacred pairing with ancient roots across Mediterranean, Egyptian, and Middle Eastern traditions. Both have documented anti-inflammatory and skin-supportive properties, and their combined history spans millennia of therapeutic use." },

  // ── New carrier oils — CAUTION pairings ──────────────────────────────────
  { a: "St John's Wort", b: 'Bergamot', rating: 'CAUTION', reason: "Both St John's Wort and non-FCF bergamot are photosensitising. Combined they significantly elevate the risk of UV-induced skin reaction. Use only FCF bergamot in this combination, and advise clients to avoid sun exposure for 12 hours after treatment." },
  { a: "St John's Wort", b: 'Lemongrass', rating: 'CAUTION', reason: "St John's Wort's photosensitising hypericin combined with lemongrass's citral content increases phototoxicity risk. Advise clients to avoid UV exposure after treatment." },
  { a: 'Neem', b: 'Ylang Ylang', rating: 'CAUTION', reason: "Neem's intensely pungent sulphurous odour completely overwhelms the delicate sweetness of ylang ylang — the blend will be therapeutically valid but aromatically compromised. Only combine if the therapeutic goal outweighs the aromatic outcome." },
  { a: 'Neem', b: 'Jasmine Absolute', rating: 'CAUTION', reason: "Neem's pungent sulphurous odour destroys jasmine's precious, complex aromatic character. Given jasmine absolute's exceptional cost, this is a poor value pairing — use a more odour-neutral carrier with jasmine." },
  { a: 'Neem', b: 'Rose Otto', rating: 'CAUTION', reason: "Neem's powerful odour is incompatible with rose otto's delicate, complex floral chemistry. The therapeutic combination is valid for skin conditions, but the aromatic result is unpleasant and represents poor use of an expensive oil." },
  { a: 'Arnica', b: 'Clove Bud', rating: 'CAUTION', reason: "Both are active on inflamed tissue. Clove bud's high eugenol content may cause additional irritation to already-compromised, injured skin. Reduce clove bud to 0.25% maximum in arnica-based blends." },
  { a: 'Borage Seed', b: 'Castor', rating: 'CAUTION', reason: "Both are heavy, slow-absorbing oils. Combined, their occlusive properties can significantly intensify the absorption of any essential oils in the blend — reduce EO dilutions by half when using this carrier combination." },
  { a: 'Wheat Germ', b: 'Castor', rating: 'CAUTION', reason: "An extremely heavy and occlusive combination that creates very slow absorption. Any essential oils blended into this carrier mix will have prolonged skin contact — reduce EO dilutions accordingly and avoid on sensitive skin." },
]

// ─── UNSAFE Pairs (from scripts/unsafe-pairs.ts) ─────────────────────────────
const UNSAFE_PAIRINGS: Array<{ a: string; b: string; reason: string }> = [
  {
    a: 'Clove Bud',
    b: 'Rosehip Seed',
    reason: 'Clove Bud contains high eugenol content (80–90%) which can cause severe sensitisation when combined with the linoleic acid in Rosehip Seed on damaged or sensitive skin. Risk of chemical burns on broken skin.',
  },
  {
    a: 'Clove Bud',
    b: 'Evening Primrose',
    reason: 'Eugenol in Clove Bud reacts adversely with the high GLA content in Evening Primrose, increasing skin sensitisation risk to unacceptable levels.',
  },
  {
    a: 'Clove Bud',
    b: 'Tamanu',
    reason: 'Eugenol in Clove Bud combined with calophyllolide in Tamanu significantly raises the risk of severe skin sensitisation and allergic reaction.',
  },
  {
    a: 'Peppermint',
    b: 'Castor',
    reason: 'The high menthol content in Peppermint is intensified by Castor\'s occlusive nature, creating a delivery system that can cause cold-burn sensations and skin irritation, particularly on sensitive areas.',
  },
  {
    a: 'Eucalyptus',
    b: 'Peppermint',
    reason: 'Both oils are high in 1,8-cineole and menthol respectively. Combined at massage dilutions, they can cause respiratory distress and skin sensitisation, particularly around the face and neck.',
  },
]

// ─── Main Seed Function ───────────────────────────────────────────────────────

async function main() {
  console.log('Seeding oils...')

  const allOilData = [
    ...CARRIER_OILS.map((o) => ({ ...o, type: 'CARRIER' as const })),
    ...ESSENTIAL_OILS.map((o) => ({ ...o, type: 'ESSENTIAL' as const })),
  ]

  for (const oil of allOilData) {
    await prisma.oil.upsert({
      where: { name: oil.name },
      create: {
        name: oil.name,
        botanicalName: oil.botanicalName,
        type: oil.type,
        origin: oil.origin,
        history: oil.history,
        description: oil.description,
        benefits: oil.benefits,
        contraindications: oil.contraindications,
        aroma: oil.aroma,
        consistency: 'consistency' in oil ? oil.consistency : null,
        absorbency: 'absorbency' in oil ? oil.absorbency : null,
        shelfLifeMonths: 'shelfLifeMonths' in oil ? oil.shelfLifeMonths : null,
        dilutionRateMax: 'dilutionRateMax' in oil ? oil.dilutionRateMax : null,
      },
      update: {
        botanicalName: oil.botanicalName,
        origin: oil.origin,
        history: oil.history,
        description: oil.description,
        benefits: oil.benefits,
        contraindications: oil.contraindications,
        aroma: oil.aroma,
        consistency: 'consistency' in oil ? oil.consistency : null,
        absorbency: 'absorbency' in oil ? oil.absorbency : null,
        shelfLifeMonths: 'shelfLifeMonths' in oil ? oil.shelfLifeMonths : null,
        dilutionRateMax: 'dilutionRateMax' in oil ? oil.dilutionRateMax : null,
      },
    })
  }

  console.log(`  ✓ Upserted ${allOilData.length} oils`)

  const allOils = await prisma.oil.findMany({ select: { id: true, name: true } })
  const byName = new Map(allOils.map((o) => [o.name, o.id]))

  console.log('Seeding notable pairings...')
  let pairingCount = 0

  for (const p of NOTABLE_PAIRINGS) {
    const idA = byName.get(p.a)
    const idB = byName.get(p.b)
    if (!idA || !idB) { console.warn(`  Skipping: ${p.a} or ${p.b} not found`); continue }
    const [sortedA, sortedB] = [idA, idB].sort()
    await prisma.oilPairing.upsert({
      where: { oilAId_oilBId: { oilAId: sortedA, oilBId: sortedB } },
      create: { oilAId: sortedA, oilBId: sortedB, rating: p.rating, reason: p.reason },
      update: { rating: p.rating, reason: p.reason },
    })
    pairingCount++
  }

  console.log('Seeding UNSAFE overrides...')

  for (const p of UNSAFE_PAIRINGS) {
    const idA = byName.get(p.a)
    const idB = byName.get(p.b)
    if (!idA || !idB) { console.warn(`  Skipping UNSAFE: ${p.a} or ${p.b} not found`); continue }
    const [sortedA, sortedB] = [idA, idB].sort()
    await prisma.oilPairing.upsert({
      where: { oilAId_oilBId: { oilAId: sortedA, oilBId: sortedB } },
      create: { oilAId: sortedA, oilBId: sortedB, rating: 'UNSAFE', reason: p.reason },
      update: { rating: 'UNSAFE', reason: p.reason },
    })
    pairingCount++
  }

  console.log(`  ✓ Upserted ${pairingCount} notable pairings`)
  console.log('\nSeed complete.')
  console.log(`  Total oils: ${await prisma.oil.count()}`)
  console.log(`  Total pairings: ${await prisma.oilPairing.count()}`)

  await prisma.$disconnect()
  await pool.end()
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
